travis:
  secure:
    BINSTAR_TOKEN: H1JDLg0rn5BUgo489OSKsHFh0YnPe10Xx/QEfxWpUVoJ4N6xmTurIwgAlljYGVFvV16HWY00SrHxUVrDsa0eO3MnwPDAGB8i0wk9WRMhwzvvODoe3va7hp/3e77s/AtYofgiUq/jK8vHy/P709v9KUyTD9qa0sO08TLCuWr0uJcVf6skX9yzscumdiiKhVQd65EzbsAUJOnYB81XVa5CARvwT02H//EWgY1lj6tQp2XBR9iRpxlkEf5RUoV4FGR1V9f289t1B+dBvDrtFIvbH2A/uCWdkXVMJrm12zdj4fYCJT7QY6inPSSSqZXJ2c8Fu4jO1UDbjmhmT8fFU6jKRjKEa5Wdt6fWcN5ONcwbwGmsGl8ZvLuh0g37IxrWDr8bj6noX3GStjPGuA+FLEpv1SRORhwm9cyH/aYcia4d4T0rHTGwn5HQi6IeZ+D7DKYjEd++96dGcGQ2JCHGHxZ+HfSHAU24RkxDdXPw74qNPOASketjUxoDBjbNXG1yFRJkABXG8dpb4YbbIfNedQCdrA0KVgWUfxrXtYWSqDzcs4KBnIv/1jY2gD4HoPNdl7ANwcxnAbM33IL83qtc2RuqJWJGhQtuzVQADTGNo9KRZEPruleiybqPKquD1HOaRcvyLHAmZqihzD0MkQ6ecJrjXH5oiS416kcolwvkNnHdPOs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
